# Generated by Django 2.1 on 2018-11-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictuures',
            new_name='Pictures',
        ),
    ]
